trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    filePath: 'start_simulation.sh'
    arguments: >
      $(gatlingEnterpriseUrl)
      $(apiToken)
      $(simulationId)
